package RestaurantMain;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.net.URL;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kendall Vargas
 */
public class Restaurant extends javax.swing.JFrame {

    // model for products
    DefaultTableModel modelProducts = new DefaultTableModel();
    // model for the cart
    DefaultTableModel modelCart = new DefaultTableModel();

    // for the first product list
    private static final String JSON_PRODUCTS = "products.json";
    private static final String FILE_PRODUCTS = "products.txt";

    // for the second list that saves the total of each product
    private static final String JSON_ORDERS = "orders.json";
    private static final String FILE_ORDERS = "orders.txt";

    // bool set to true
    static boolean fileExistingProduct = true;
    static boolean fileExistingOrder = true;

    // GSON object
    static Gson gson = new Gson();

    // date with time in MM/DD/YY format and the minute in which the order was added
    LocalDateTime myDateObj = LocalDateTime.now();
    DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("MM-dd-yyyy HH:mm:ss");
    String formattedDate = myDateObj.format(myFormatObj);

    // arraylist of products
    static List<Product> listProducts = new ArrayList<>();
    //arraylist of the products added to the cart
    static List<Product> cartProducts = new ArrayList<>();

    // Creating the arrayList with all the orders added by the user
    static List<String> totalOrderReport = new ArrayList<>();

    // number of columns that the product objects will have
    static final int NUM_COLUMN = 2;

    Order order;

    public Restaurant() {
        initComponents();
        formIcon();

        modelProducts.addColumn("Product");
        modelProducts.addColumn("Price");
        updateProductTable();

        modelCart.addColumn("Product");
        modelCart.addColumn("Total Price");
        updateCartTable();

    }
    
    public final void formIcon(){
        URL url = getClass().getResource("/Images/favicon.png");
        ImageIcon form_icon = new ImageIcon(url);
        setIconImage(form_icon.getImage());
    }

    public void updateProductTable() {

        while (modelProducts.getRowCount() > 0) {
            modelProducts.removeRow(0);
        }

        for (Product listProd : listProducts) {
            Object column[] = new Object[NUM_COLUMN];
            column[0] = listProd.getProductName();
            column[1] = listProd.getProductPrice();

            // I add the columns to the model
            modelProducts.addRow(column);
        }

        // I set this model to my GUI table
        tablaProductos.setModel(modelProducts);

    }

    public void updateCartTable() {

        while (modelCart.getRowCount() > 0) {
            modelCart.removeRow(0);
        }

        for (Product cartList : cartProducts) {
            Object column[] = new Object[NUM_COLUMN];
            column[0] = cartList.getProductName();
            column[1] = cartList.getProductPrice();

            // I add the columns to the model
            modelCart.addRow(column);
        }

        // I set this model to my GUI table
        tablaCarrito1.setModel(modelCart);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldPrecio = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAgregarCarrito = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        spinnerCantProd = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        fieldDuenioCuenta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldDescuento = new javax.swing.JTextField();
        agregarProductoFinal = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCarrito1 = new javax.swing.JTable();
        fieldNombreProducto = new javax.swing.JTextField();
        btnBorrarFields = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaTextoReporte = new javax.swing.JTextArea();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setForeground(new java.awt.Color(153, 153, 153));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(100, 180));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create a new Product");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Insert the name of the product:");

        fieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        fieldNombre.setForeground(new java.awt.Color(0, 0, 0));
        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Insert the price of the product (in USD):");

        fieldPrecio.setBackground(new java.awt.Color(255, 255, 255));
        fieldPrecio.setForeground(new java.awt.Color(0, 0, 0));
        fieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPrecioActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Create");
        btnAgregar.setToolTipText("");
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Products:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(fieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(121, 121, 121))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(fieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnAgregar)))
                .addGap(527, 527, 527))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Add a Product", jPanel1);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Create a new order");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Insert the name of the product:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter the amount of the product consumed:");

        btnAgregarCarrito.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarCarrito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregarCarrito.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cartIcon.png"))); // NOI18N
        btnAgregarCarrito.setText("Add");
        btnAgregarCarrito.setToolTipText("Add entire order to registry!");
        btnAgregarCarrito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarCarrito.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAgregarCarrito.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarritoActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Order information:");

        spinnerCantProd.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter the name of the owner of the order:");

        fieldDuenioCuenta.setBackground(new java.awt.Color(255, 255, 255));
        fieldDuenioCuenta.setForeground(new java.awt.Color(0, 0, 0));
        fieldDuenioCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDuenioCuentaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter the discount code:");

        fieldDescuento.setBackground(new java.awt.Color(255, 255, 255));
        fieldDescuento.setForeground(new java.awt.Color(0, 0, 0));
        fieldDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescuentoActionPerformed(evt);
            }
        });

        agregarProductoFinal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarProductoFinal.setText("Add Product");
        agregarProductoFinal.setToolTipText("Add all the products that were consumed, move on to the next section once completed!");
        agregarProductoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoFinalActionPerformed(evt);
            }
        });

        tablaCarrito1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Total Price"
            }
        ));
        jScrollPane4.setViewportView(tablaCarrito1);

        fieldNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreProductoActionPerformed(evt);
            }
        });

        btnBorrarFields.setBackground(new java.awt.Color(0, 0, 0));
        btnBorrarFields.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBorrarFields.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarFields.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnBorrarFields.setText("Clear");
        btnBorrarFields.setToolTipText("Clear the contents of the fields!");
        btnBorrarFields.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrarFields.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBorrarFields.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBorrarFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarFieldsActionPerformed(evt);
            }
        });

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        textArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane5.setViewportView(textArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agregarProductoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(fieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(spinnerCantProd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 156, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(fieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldDuenioCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnBorrarFields, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinnerCantProd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(fieldNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addComponent(agregarProductoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDuenioCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBorrarFields, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Add an order", jPanel2);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Record of total orders");

        btnGenerarReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reportIcon.png"))); // NOI18N
        btnGenerarReporte.setText("Generate Report");
        btnGenerarReporte.setToolTipText("Generate a new report with all the orders registered.");
        btnGenerarReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerarReporte.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnGenerarReporte.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        areaTextoReporte.setEditable(false);
        areaTextoReporte.setColumns(20);
        areaTextoReporte.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        areaTextoReporte.setLineWrap(true);
        areaTextoReporte.setRows(5);
        areaTextoReporte.setWrapStyleWord(true);
        areaTextoReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(areaTextoReporte);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel11)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerarReporte)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dsiplay Order Report", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCodDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCodDescuentoActionPerformed
    }//GEN-LAST:event_fieldCodDescuentoActionPerformed

    private void fieldDuenioOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDuenioOrdenActionPerformed
    }//GEN-LAST:event_fieldDuenioOrdenActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // process for product arraylist
        saveFileTxt();
        serializationJson();

        // process for order arraylist
        saveFileOrders();
        serializationString();

    }//GEN-LAST:event_formWindowClosing

    private void fieldNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreProdUCTOActionPerformed

    }//GEN-LAST:event_fieldNombreProdUCTOActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnGenerarReporte.setEnabled(false);

        // process to save the arraylist of products
        createJson();
        deserializationJson();
        // fill the table with the array that fills
        updateProductTable();

        // process to save the array of orders
        createJsonOrder();
        deserializationString();
        // fill the table with the array that fills
        fillOrderReport();


    }//GEN-LAST:event_formWindowOpened

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed

        try {
            // save the report list to areaText
            fillOrderReport();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }

    }//GEN-LAST:event_btnGenerarReporteActionPerformed

   
    private void btnBorrarFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarFieldsActionPerformed
        // Clear all fields and reset the spinner to 1
        try {
            fieldNombreProducto.setText("");
            spinnerCantProd.setValue(1);
            fieldDuenioCuenta.setText("");
            fieldDescuento.setText("");

            // clear product table
            cartProducts.clear();
            while (modelCart.getRowCount() > 0) {
                modelCart.removeRow(0);
            }

        } catch (Exception e) {
            e.printStackTrace(System.out);
            JOptionPane.showMessageDialog(this, "Error!");
        }

        // delete the textArea field
        textArea.setText("");
    }//GEN-LAST:event_btnBorrarFieldsActionPerformed

//GEN-FIRST:event_fieldNombreProductoActionPerformed

//GEN-LAST:event_fieldNombreProductoActionPerformed

    private void agregarProductoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoFinalActionPerformed
        boolean foundProduct = false;

        try {

            Product product1;

            // convert the return of the .getValue() object to an int
            int value = (int) spinnerCantProd.getValue();

            String productName = fieldNombreProducto.getText();

            // validation so that it does not enter when the list is empty
            if (!listProducts.isEmpty()) {

                for (Product list : listProducts) {

                    if (productName.equals(list.getProductName())) {

                        // I multiply the quantity by the price of that product consumed
                        double result = list.getProductPrice() * value;

                        // creating a new object of type Product but this time storing the price consumed
                        product1 = new Product(productName, result);
                        // Adding the product with the price based on consumption, in the cart array
                        cartProducts.add(product1);
                        foundProduct = true;

                        // filling out the model's table
                        updateCartTable();

                        break;
                    }

                    if (foundProduct) {
                        break;
                    }

                }

                if (!foundProduct) {
                    JOptionPane.showMessageDialog(this, "Product not found!!");

                }

                order = new Order();

                order.setDate(formattedDate);
                // set what is missing from the Order constructor, the 2 arrayLists
                order.setProductList(listProducts);
                order.setProductCart(cartProducts);

            } else {
                JOptionPane.showMessageDialog(this, "Products are needed before placing an order!");
            }
        } catch (Exception e) {
            e.printStackTrace(System.out);
            JOptionPane.showMessageDialog(this, "Error!");

        }

    }//GEN-LAST:event_agregarProductoFinalActionPerformed

    private void fieldDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescuentoActionPerformed

    }//GEN-LAST:event_fieldDescuentoActionPerformed

    private void fieldDuenioCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDuenioCuentaActionPerformed

    }//GEN-LAST:event_fieldDuenioCuentaActionPerformed

    private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarritoActionPerformed

        try {
            order.setClientName(fieldDuenioCuenta.getText());
            double discount = 0;
            String discountString = fieldDescuento.getText();
            discount = switch (discountString) {
                case "DSC5" ->
                0.05;
                case "DSC10" ->
                0.10;
                case "DSC15" ->
                0.15;
                default ->
                0;
            };

            // Setting the order number automatically
            String orderStart = "ORD #";
            int iterator = countIndex();
            String iteratorString = String.valueOf(iterator);
            String orderFinal = orderStart + iteratorString;
            order.setOrderNumber(orderFinal);

            // setting the discount
            order.setDiscount(discount);

            if (order.getClientName().isBlank() || discountString.isBlank() || order.getProductCart().isEmpty()) {
                JOptionPane.showMessageDialog(this, "INVALID DATA, TRY AGAIN!");
            } else {
                // This saves all the reports in an array so taht I can display them later in menu 3
                totalOrderReport.add(order.totalCalculation());
                btnGenerarReporte.setEnabled(true);

                // This saves the individual report of each order in a variable
                String report = order.totalCalculation();
                // This sets the report to a text area.
                textArea.setText(report);
            }

        } catch (Exception e) {
            e.printStackTrace(System.out);
            JOptionPane.showMessageDialog(this, "ERROR");
        }
    }//GEN-LAST:event_btnAgregarCarritoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        try {
            Product prod = new Product();
            String nombreProducto = fieldNombre.getText();
            boolean duplicateProduct = false;
            
            for (Product listProduct : listProducts) {
                if(listProduct.getProductName().equals(nombreProducto)) {
                    duplicateProduct = true;
                    break;
                }
            }
            
            // check if the product is already added or not, if it is, it will show an error message and won't add the product again
            if(!duplicateProduct){
                prod.setProductName(fieldNombre.getText());
                prod.setProductPrice(Double.parseDouble(fieldPrecio.getText()));

                // add the product to the arrayList
                listProducts.add(prod);

                // refreshing the table
                updateProductTable(); 
            } else{
                JOptionPane.showMessageDialog(this, "The product already exists!");
            }
   

        } catch (NumberFormatException e) {
            e.printStackTrace(System.out);
            JOptionPane.showMessageDialog(this, "INVALID DATA, TRY AGAIN!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR ADDING PRODUCT");
            e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void fieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPrecioActionPerformed

    }//GEN-LAST:event_fieldPrecioActionPerformed

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed

    }//GEN-LAST:event_fieldNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }

    /* ---------------------- Methods and Functions ---------------------- */
    
    public static void fillOrderReport() {

        // here I clean the report so that it does not have the values ​​prior to loading, since when loading the deserialization it loads the variable 'report'
        String report = "";
        for (String reportTotal : totalOrderReport) {
            report += reportTotal;
        }

        // save all report text in GUI areaText variable
        areaTextoReporte.setText(report);
    }

    public static void createJson() {

        // I need to create the file from scratch so that it doesn't throw an exception
        File file = new File(JSON_PRODUCTS);
        if (!file.exists()) {
            try {
                file.createNewFile();
                // write an initial empty JSON
                try (Writer writer = new FileWriter(file)) {
                    writer.write("[]"); // JSON empty
                    fileExistingProduct = false;
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public static void createJsonOrder() {

        // I need to create the file from scratch so that it doesn't throw an exception
        File file = new File(JSON_ORDERS);
        if (!file.exists()) {
            try {
                file.createNewFile();
                // write an initial empty JSON
                try (Writer writer = new FileWriter(file)) {
                    writer.write("[]"); // JSON empty
                    fileExistingOrder = false;
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public static void deserializationJson() {
        /* DESERIALIZATION, it is done first because I need to read the JSON
           and transform that data into an object to continue using it */
        if (fileExistingProduct) {
            // only read if the file exists

            // Read JSON from file and deserialize
            try (Reader reader = new FileReader(JSON_PRODUCTS)) {
                // get the type of list being read to be reused and maintain the structure
                java.lang.reflect.Type listType = new TypeToken<ArrayList<Product>>() {
                }.getType();
                listProducts = gson.fromJson(reader, listType);

            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public static void saveFileTxt() {
        // Save in a txt file
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PRODUCTS))) {
            // loop through all objects and save them
            for (Product prod : listProducts) {
                String productString = "Product: " + prod.getProductName() + ", " + "Price: " + prod.getProductPrice() + "\n";
                // write the entire string to the file
                writer.write(productString);
                //writer.close();
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void serializationJson() {
        // Serialize to JSON and save to json file
        try (Writer writer = new FileWriter(JSON_PRODUCTS)) {
            // This converts the entire array to Json
            gson.toJson(listProducts, writer);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void deserializationString() {
        if (fileExistingProduct) {
            try (Reader reader = new FileReader(JSON_ORDERS)) {
                // get the type of list being read for reuse and maintaining the data structure
                java.lang.reflect.Type listType = new TypeToken<ArrayList<String>>() {
                }.getType();
                // load list by transforming Json file to arrayList
                totalOrderReport = gson.fromJson(reader, listType);

            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public static void serializationString() {
        try (Writer writer = new FileWriter(JSON_ORDERS)) { // instance to write to file
            // write the order report in json format to .json
            gson.toJson(totalOrderReport, writer);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void saveFileOrders() {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_ORDERS))) {
            String text = "";
            for (String report : totalOrderReport) {
                // Assign the array of strings to a variable
                text = report;
                writer.write(text); // write the array of strings to the .txt file
            }

        } catch (Exception e) {
        }
    }

    // This function is to count the index of the report List and assign this index to the corresponding order number.
    public static int countIndex() {
        int orderNumber = 0;
        for (String report : totalOrderReport) {
            orderNumber++; // count the array of orders to get the index and assign the order # automatically
        }
        // add +1 to the index, so that it matches the current order number
        orderNumber++;
        return orderNumber;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProductoFinal;
    private static javax.swing.JTextArea areaTextoReporte;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JButton btnBorrarFields;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JTextField fieldDescuento;
    private javax.swing.JTextField fieldDuenioCuenta;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldNombreProducto;
    private javax.swing.JTextField fieldPrecio;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner spinnerCantProd;
    private javax.swing.JTable tablaCarrito1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
